theme = "autumn"

[editor]
line-number = "absolute"
mouse = false
text-width = 85

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "<->"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "hidden"
insert = "bar"
select = "block"

[editor.file-picker]
hidden = false
